[package]
name = "bms"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.6"
lazy_static = "1.4.0"
itertools = "0.10.0" 
read_input = "0.8.4"
radix_fmt = "1"

[lib]
crate-type = ["cdylib"]